# Generated by Django 5.2.15 on 2026-07-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('grade_level', models.CharField(default='Grade 10', max_length=50)),
                ('attendance', models.IntegerField(default=0)),
                ('grade_score', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='Low', max_length=20)),
            ],
            options={
                'db_table': 'students',
                'managed': True,
            },
        ),
    ]
